version: '3.8'

services:
  nodejs:
    image: node:18
    container_name: nodejs
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm start"
